# Use the official Gremlin Console image as the base
FROM tinkerpop/gremlin-console:latest

COPY . ./


# Add the wait-for-it.sh script

USER root
RUN chmod +x ./wait-for-it.sh ./docker-entrypoint.sh
USER gremlin

# Set the entrypoint to use wait-for-it.sh
ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["sh", "-c", "./bin/gremlin.sh -e /app/preload-graph.groovy && tail -f /dev/null"]